[Bypass]
; Где BRBYPASS слушает SA-MP клиента (локальный "сервер" для клиента)
listen_host = 127.0.0.1
listen_port = 7777

[BlackRussia]
; Куда BRBYPASS ретранслирует пакеты (реальный сервер Black Russia)
host = 80.66.82.114
port = 5125

[Auth]
; Логин/пароль аккаунта Black Russia.
; Если AUTH_AUTO=true и сервер прислал окно авторизации — пароль уйдёт автоматически.
password = 123123
auth_auto = true
; Авторегистрация нового аккаунта (если сервер предложил регистрацию)
reg_auto = true
email =
referral = create_gaming
gender = 0
skin = 78

[Log]
verbose = false
; вывод в консоль

[Relay]
; Если false — RPC TOGGLE_PLAYER_CONTROLLABLE (BR 428 -> SAMP 15) дропается и клиенту не релеится, проще говоря игрок не фризится
toggle_player_controllable = false
; Если true — любой дамаг игнорируется: RPC SET_PLAYER_HEALTH (BR 387 -> SAMP 14)
; и SET_PLAYER_ARMOUR (BR 315 -> SAMP 66) со значением < 100 дропаются, хп всегда 100
damage_ignore = false
