PORT = 5125

MAX_DATAGRAM_BYTES = 500


class IncomingPacketID:


    OPEN_CONNECTION_REPLY = 0x07
    CONNECTION_REQUEST_ACCEPTED = 0x0E
    AUTH_KEY = 0x05

    INTERNAL_PING = 0x02
    CONNECTED_PONG = 0x0A
    DISCONNECTION_NOTIFICATION = 0x0F
    CONNECTION_LOST = 0x11
    CONNECTION_ATTEMPT_FAILED = 0x14
    CONNECTION_BANNED = 0x19
    INVALID_PASSWORD = 0x1A

    USER_INTERFACE_SYNC = 0x1B
    RPC = 0x0B


class OutgoingPacketID:


    OPEN_CONNECTION_REQUEST = 0x04
    CONNECTION_REQUEST = 0x08
    AUTH_KEY_RESPONSE = 0x06
    NEW_INCOMING_CONNECTION = 0x14
    DISCONNECTION_NOTIFICATION = 0x0F
    INTERNAL_PING = 0x02
    CONNECTED_PONG = 0x0A
    RECEIVED_STATIC_DATA = 0x08

    USER_INTERFACE_SYNC = 0x1B
    RPC = 0x0B


class RPC:
    SERVER_COMMAND = 378
    PICKED_UP_PICKUP = 436
    PICKED_UP_INTERACT = 413
    DEATH = 371
    SET_SPAWN_INFO = 372
    SERVER_JOIN = 401
    SERVER_QUIT = 326
    INIT_GAME = 421
    CLIENT_JOIN = 67
    REQUEST_CLASS = 361
    REQUEST_SPAWN = 344
    SPAWN = 441
    CHAT = 414
    CICK_TEXTDRAW = 437
    ENTER_VEHICLE = 382
    EXIT_VEHICLE = 409
    UPDATE_SCORES_PINGS_IPS = 374
    CONNECTION_REJECTED = 319
    CLIENT_MESSAGE = 360
    WORLD_PLAYER_ADD = 419
    WORLD_PLAYER_REMOVE = 325
    WORLD_VEHICLE_ADD = 329
    WORLD_VEHICLE_REMOVE = 397
    DIALOG_RESPONSE = 514
    SCR_DIALOG_BOX = 347


    CREATE_PICKUP = 377
    DESTROY_PICKUP = 373
    SCR_CREATE_3D_TEXT_LABEL = 432
    SCR_PUT_PLAYER_IN_VEHICLE = 353
    SCR_REMOVE_PLAYER_FROM_VEHICLE = 362
    SCR_GIVE_PLAYER_MONEY = 362
    SCR_DELETE_3D_TEXT_LABEL = 309
    SCR_SET_MAP_ICON = 417
    SCR_DISABLE_MAP_ICON = 322
    SCR_SET_INTERIOR = 434
    SCR_SET_CAMERA_POS = 310
    SCR_SET_CAMERA_LOOK_AT = 357
    SCR_SET_VEHICLE_POS = 412
    SCR_SET_VEHICLE_Z_ANGLE = 325
    SCR_VEHICLE_PARAMS = 411
    SCR_SET_PLAYER_POS = 448
    SCR_SET_PLAYER_POS_FIND_Z = 341
    SCR_SET_PLAYER_FACING_ANGLE = 352
    SCR_SET_PLAYER_HEALTH = 387
    SCR_SET_PLAYER_ARMOUR = 315
    SCR_SET_WEAPON_AMMO = 303
    SCR_GIVE_PLAYER_WEAPON = 433
    SCR_RESET_PLAYER_WEAPONS = 334
    SCR_SET_PLAYER_VELOCITY = 335
    SCR_SET_VEHICLE_VELOCITY = 334
    SCR_SET_PLAYER_SKIN = 400
    SCR_SHOW_TEXT_DRAW = 418
    SCR_HIDE_TEXT_DRAW = 354
    SCR_TEXT_DRAW_SET_STRING = 349
    SCR_TOGGLE_SELECT_TEXTDRAW = 376
    SCR_DISPLAY_GAME_TEXT = 415
    SCR_SET_WORLD_BOUNDS = 347
    SCR_TOGGLE_PLAYER_CONTROLLABLE = 428
    SCR_PLAY_AUDIO_STREAM = 313
    SCR_STOP_AUDIO_STREAM = 512
    WORLD_PLAYER_DEATH = 412
    GAME_MODE_RESTART = 367
    SET_CHECKPOINT = 440
    DISABLE_CHECKPOINT = 421
    SET_RACE_CHECKPOINT = 338
    DISABLE_RACE_CHECKPOINT = 304
    SCR_ADD_GANG_ZONE = 358
    SCR_REMOVE_GANG_ZONE = 332
    SCR_FLASH_GANG_ZONE = 374
    SCR_STOP_FLASH_GANG_ZONE = 385
    SCR_APPLY_ANIMATION = 319
    SCR_CLEAR_ANIMATIONS = 306
    SCR_SET_GRAVITY = 305
    WEATHER = 411
    WORLD_TIME = 365
    CHAT_BUBBLE = 375
    PLAY_AUDIO_STREAM = 313
    STOP_AUDIO_STREAM = 512
    SET_PLAYER_NAME = 384

class PacketReliability:


    UNRELIABLE = 0
    UNRELIABLE_SEQUENCED = 1
    RELIABLE = 2
    RELIABLE_ORDERED = 3
    RELIABLE_SEQUENCED = 4


class PacketPriority:
    SYSTEM_PRIORITY = 0
    HIGH_PRIORITY = 1
    MEDIUM_PRIORITY = 2
    LOW_PRIORITY = 3
    NUMBER_OF_PRIORITIES = 4


ORDERING_METADATA_RELIABILITIES = frozenset({
    PacketReliability.UNRELIABLE_SEQUENCED,
    PacketReliability.RELIABLE_ORDERED,
    PacketReliability.RELIABLE_SEQUENCED,
})

RELIABLE_RELIABILITIES = frozenset({
    PacketReliability.RELIABLE,
    PacketReliability.RELIABLE_ORDERED,
    PacketReliability.RELIABLE_SEQUENCED,
})


OFFLINE_PACKET_IDS = frozenset({
    OutgoingPacketID.OPEN_CONNECTION_REQUEST,
    IncomingPacketID.OPEN_CONNECTION_REPLY,
})


OPEN_CONNECTION_REQUEST_BODY = b"\x42\x52"


AUTH_KEY_LEN = 0x60

class IncomingInterfaceSync:
    AUTH = 0x0026
    SPAWN_SELECT = 0x0032
    CINEMATIC = 0x004C
    DONATE_MENU = 0x0016
    CASES = 0x0049
    NOTIFICATION = 0x000D
    CALL_NOTIFICATION = 0x0041
    QUEST_TASK = 0x0027
    NPC_DIALOG = 0x003F
    DIALOG_NPC = 0x0072
    REWARD = 0x004A


class OutgoingInterfaceSync:
    AUTH = 0x0026
    SPAWN_SELECT = 0x0032
    CINEMATIC = 0x004C
    DONATE_MENU = 0x0016
    CASES = 0x0049
    NOTIFICATION = 0x000D


CLIENT_JOIN_HEADER_HEX = "874A8B6B020B06000000"
