MAX_DATAGRAM_BYTES = 500


class PacketID:
    INTERNAL_PING = 6
    PING = 7
    PING_OPEN_CONNECTIONS = 8
    CONNECTED_PONG = 9
    REQUEST_STATIC_DATA = 10
    CONNECTION_REQUEST = 11
    AUTH_KEY_RESPONSE = 12
    AUTH_KEY = 12
    BROADCAST_PINGS = 14
    RPC_MAPPING = 17
    SET_RANDOM_NUMBER_SEED = 19
    RPC = 20
    RPC_REPLY = 21
    DETECT_LOST_CONNECTIONS = 23
    OPEN_CONNECTION_REQUEST = 24
    OPEN_CONNECTION_REPLY = 25
    OPEN_CONNECTION_COOKIE = 26
    RSA_PUBLIC_KEY_MISMATCH = 28
    CONNECTION_ATTEMPT_FAILED = 29
    NEW_INCOMING_CONNECTION = 30
    NO_FREE_INCOMING_CONNECTIONS = 31
    DISCONNECTION_NOTIFICATION = 32
    CONNECTION_LOST = 33
    CONNECTION_REQUEST_ACCEPTED = 34
    CONNECTION_BANNED = 36
    INVALPASSWORD = 37
    MODIFIED_PACKET = 38
    PONG = 39
    TIMESTAMP = 40
    RECEIVED_STATIC_DATA = 41
    ADVERTISE_SYSTEM = 55


    VEHICLE_SYNC = 200
    RCON_COMMAND = 201
    WEAPONS_UPDATE = 204
    STATS_UPDATE = 205
    BULLET_SYNC = 206
    PLAYER_SYNC = 207
    MARKERS_SYNC = 208
    UNOCCUPIED_SYNC = 209
    TRAILER_SYNC = 210
    PASSENGER_SYNC = 211
    SPECTATOR_SYNC = 212
    AIM_SYNC = 203


class RPC:
    SERVER_COMMAND = 50
    PICKED_UP_PICKUP = 131
    SET_SPAWN_INFO = 68
    SERVER_JOIN = 137
    SERVER_QUIT = 138
    INIT_GAME = 139
    CLIENT_JOIN = 25
    NPC_JOIN = 54
    DEATH = 53
    REQUEST_CLASS = 128
    REQUEST_SPAWN = 129
    SPAWN = 52
    CHAT = 101
    ENTER_VEHICLE = 26
    EXIT_VEHICLE = 154
    UPDATE_SCORES_PINGS_IPS = 155
    CONNECTION_REJECTED = 130
    CLIENT_MESSAGE = 93
    WORLD_PLAYER_ADD = 32
    WORLD_PLAYER_REMOVE = 163
    WORLD_VEHICLE_ADD = 164
    WORLD_VEHICLE_REMOVE = 165
    DIALOG_RESPONSE = 62
    SCR_DIALOG_BOX = 61


    CREATE_PICKUP = 95
    DESTROY_PICKUP = 63
    CREATE_3D_TEXT_LABEL = 36
    DELETE_3D_TEXT_LABEL = 58
    PUT_PLAYER_IN_VEHICLE = 70
    REMOVE_PLAYER_FROM_VEHICLE = 71
    GIVE_PLAYER_MONEY = 18
    RESET_PLAYER_MONEY = 20
    SET_MAP_ICON = 56
    REMOVE_MAP_ICON = 144
    SET_INTERIOR = 156
    SET_CAMERA_POS = 157
    SET_CAMERA_LOOK_AT = 158
    SET_VEHICLE_POS = 159
    SET_VEHICLE_Z_ANGLE = 160
    SET_VEHICLE_PARAMS = 161
    SET_VEHICLE_PARAMS_EX = 24
    SET_PLAYER_POS = 12
    SET_PLAYER_POS_FIND_Z = 13
    SET_PLAYER_NAME = 11
    SET_PLAYER_FACING_ANGLE = 19
    SET_PLAYER_HEALTH = 14
    SET_PLAYER_ARMOUR = 66
    SET_WEAPON_AMMO = 145
    SET_CAMERA_BEHIND = 162
    GIVE_PLAYER_WEAPON = 22
    RESET_PLAYER_WEAPONS = 21
    SET_PLAYER_VELOCITY = 90
    SET_VEHICLE_VELOCITY = 91
    SET_PLAYER_SKIN = 153
    SHOW_TEXT_DRAW = 134
    HIDE_TEXT_DRAW = 135
    TEXT_DRAW_SET_STRING = 105
    TOGGLE_SELECT_TEXT_DRAW = 83
    SHOW_GAME_TEXT = 73
    SET_CHECKPOINT = 107
    DISABLE_CHECKPOINT = 37
    SET_RACE_CHECKPOINT = 38
    DISABLE_RACE_CHECKPOINT = 39
    GAME_MODE_RESTART = 40
    APPLY_PLAYER_ANIMATION = 86
    CLEAR_PLAYER_ANIMATION = 87
    SET_GRAVITY = 146
    WEATHER = 152
    SET_WORLD_BOUNDS = 17
    TOGGLE_PLAYER_CONTROLLABLE = 15
    CHAT_BUBBLE = 59
    PLAY_AUDIO_STREAM = 41
    STOP_AUDIO_STREAM = 42
    WORLD_PLAYER_DEATH = 166

class PacketReliability:


    UNRELIABLE = 6
    UNRELIABLE_SEQUENCED = 7
    RELIABLE = 8
    RELIABLE_ORDERED = 9
    RELIABLE_SEQUENCED = 10


class PacketPriority:
    SYSTEM_PRIORITY = 0
    HIGH_PRIORITY = 1
    MEDIUM_PRIORITY = 2
    LOW_PRIORITY = 3
    NUMBER_OF_PRIORITIES = 4


ORDERING_METADATA_RELIABILITIES = frozenset({
    PacketReliability.UNRELIABLE_SEQUENCED,
    PacketReliability.RELIABLE_ORDERED,
    PacketReliability.RELIABLE_SEQUENCED,
})


RELIABLE_RELIABILITIES = frozenset({
    PacketReliability.RELIABLE,
    PacketReliability.RELIABLE_ORDERED,
    PacketReliability.RELIABLE_SEQUENCED,
})


OFFLINE_PACKET_IDS = frozenset({
    PacketID.OPEN_CONNECTION_REQUEST,
    PacketID.OPEN_CONNECTION_REPLY,
    PacketID.OPEN_CONNECTION_COOKIE,
})


OPEN_CONNECTION_COOKIE = 0x6969


FIXED_SAMP_AUTH_KEY = "9DA7435192B51BE"


SAMP_ENCRYPT_PORT_XOR = 0xCC


CLIENT_JOIN_IVERSION = 4057
CLIENT_JOIN_BYTE_MOD = 1
CLIENT_JOIN_CLIENT_VERSION = "0.3.7"
CLIENT_JOIN_GPCI_FACTOR = 0x3E9
